# Generated by Django 4.0.4 on 2022-05-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscte_forum', '0003_alter_comment_author_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
