# Generated by Django 4.0.4 on 2022-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscte_forum', '0004_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.CharField(default='iscte_forum/static/iscte_forum/images/pfp_default.png', max_length=256),
        ),
    ]
